workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          android_signing:
            - GDSC1
          vars:
            PACKAGE_NAME: "io.codemagic.sample.androidnative"
