name: gdsc_app
description: A new Flutter project.

publish_to: "none"

version: 1.6.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.4
  stacked: ^3.4.2
  stacked_services: ^1.4.0
  provider: ^6.1.1
  supabase: ^2.0.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  path: ^1.8.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  simple_s3: ^0.3.2
  uuid: ^4.3.3
  cached_network_image: ^3.3.1
  sentry_flutter: ^7.16.0
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.0.1
  onesignal_flutter: ^5.1.0

  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  form_builder_validators: ^9.1.0
  filter_list: ^1.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^3.0.1
  stacked_cli: 1.12.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/icons/events/
    - assets/icons/navigation/
    - assets/icons/navigation2/
    - assets/icons/profile/
    - assets/images/
    - assets/images/events/
    - assets/images/GDSC/
    - assets/images/home/
