name: gdsc_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-51.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.0.2
  stacked: ^3.3.0
  stacked_services: ^1.0.4
  rxdart:
  provider:
# Supabase
  supabase: ^0.3.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.8
  image_picker: ^0.8.7+5
  path: ^1.8.3
  flutter_svg_provider: ^1.0.3
  flutter_spinkit: ^5.2.0
  # Carousel
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  simple_s3: ^0.3.2
  aws_s3_upload: ^1.5.0
  uuid: ^3.0.7
  form_builder_validators: ^9.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: "assets/icons/appicon.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/events/
    - assets/icons/navigation/
    - assets/icons/navigation2/
    - assets/icons/profile/
    - assets/images/
    - assets/images/events/
    - assets/images/GDSC/
    - assets/images/home/
