name: gdsc_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-51.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  stacked: ^3.0.0
  stacked_core: ^1.2.4
  stacked_services: ^0.9.5
  rxdart:
  provider:
  # Supabase
  supabase: ^0.3.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  stacked_generator: ^0.8.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
