name: Flutter build apk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2.11
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
